workspace:
  base: /go
  path: src/github.com/udistrital/organizacion_crud/

pipeline:

  # build and test the go program
  go:
    image: golang:1.9
    commands:
     - go get -t
     - GOOS=linux GOARCH=amd64 go build -o main
    when:

      branch: [master, develop]
      event: push

  # prepare imagedef.json and app.zip for deployment
  sed:
    image: alpine
    commands:
      - sed -i 's|SED_TAG|'${CI_COMMIT:0:7}'|' imagedef.json
      - apk -U add zip
      - zip app.zip imagedef.json
    when:

      branch: [master, develop]
      event: push
      
  # build and push docker image to docker hub
  publish_dockerhub:
    image: plugins/docker
    repo: oas0/organizacion_crud
    secrets: [ docker_username, docker_password ]
    tag:
      - ${DRONE_COMMIT:0:7}
      - latest
    when:

      branch: [master, develop]
      event: push
      
  # upload app.zip to s3 bucket for CodePipline
  publish_s3:
    image: plugins/s3
    region: "us-east-1"
    bucket: "drone-helper-bucket"
    secrets: [ drone_aws_access_key_id, drone_aws_secret_access_key ]
    source: app.zip
    target: /apps/organizacion_crud-$DRONE_BRANCH.zip
    when:
      branch: [master, develop]
      event: push      
