workspace:
  base: /go
  path: src/github.com/udistrital/organizacion_crud/

pipeline:

  # build and test the go program
  go:
    image: golang:1.9
    commands:
     - go get -t
     - GOOS=linux GOARCH=amd64 go build -o main
    when:
      branch: master
      event: push

    # build and push docker image to docker hub
  publish:
    image: plugins/docker
    repo: docker.io/oas0
    tag:
      - latest
    email: computoud@googlegroups.com
    when:
      branch: master
      event: push
