workspace:
  base: /go
  path: src/github.com/udistrital/organizacion_crud/

pipeline:

  # build and test the go program
  go:
    image: golang:1.9
    commands:
     - go get -t
     - GOOS=linux GOARCH=amd64 go build -o main
    when:
      branch: master
      event: push

    # build and push docker image to docker hub
  publish:
    image: plugins/docker
    repo: oas0/ente_crud
    tag:
      - $${COMMIT:0:7}
      - latest
    username: $$DRONE_DOCKERID_LOGIN
    password: $$DRONE_DOCKERID_PASSWORD
    email: computoud@googlegroups.com
    when:
      branch: master
      event: push
