workspace:
  base: /go
  path: src/github.com/udistrital/organizacion_crud/

pipeline:

  # build and test the go program
  go:
    image: golang:1.9
    commands:
     - go get -t
     - GOOS=linux GOARCH=amd64 go build -o main
    when:

      branch: [no_make]
      event: push

  # prepare imagedef.json and app.zip for deployment
  sed:
    image: alpine
    commands:
      - sed -i 's|SED_TAG|'${CI_COMMIT:0:7}'|' imagedef.json
      - apk -U add zip
      - zip app.zip imagedef.json
    when:

      branch: [no_make]
      event: push
      
  # build and push docker image to docker hub
  publish_dockerhub:
    image: plugins/docker
    repo: oas0/organizacion_crud
    secrets: [ docker_username, docker_password ]
    tag:
      - ${DRONE_COMMIT:0:7}
      - latest
    when:

      branch: [no_make]
      event: push
      
  # upload app.zip to s3 bucket for CodePipline
  publish_s3:
    image: plugins/s3
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: "us-east-1"
    bucket: "drone-helper-bucket"
    source: app.zip    
    target: /apps/organizacion_crud-${DRONE_BRANCH}.zip
    when:
      branch: [no_make]
      event: push
      
  #Notify results to telegram    
  notify_telegram:
    image: appleboy/drone-telegram    
    secrets: [ telegram_token, telegram_to ]
    format: markdown
    message: >
      {{#success build.status}}
        {{repo.name:_:-}}
      {{else}}
        `{{repo.owner}}/"{{repo.name}}"` [FAILURE]({{build.link}}) `{{commit.branch}}`@{{truncate commit.sha 7}}
      {{/success}}
